["protostar.config"]
protostar_version = "0.9.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]

db = [
    "src/contracts/db/db.cairo"
]

ERC20 = [
    "src/contracts/erc20/ERC20.cairo"
]

presale = [
    "src/presale.cairo"
]

NFT = [
    "src/contracts/erc721/NFT.cairo"
]

["profile.testnet.protostar.deploy"]
network="testnet"